! MIT License
! Copyright (C) 2017-2019 Daniel Prosser
! Copyright (c) 2022-2024 Jochen Guenzel

module commons

  ! global commons 


  ! needed here for airfoil type 
  use shape_bezier,       only: bezier_spec_type  
  use shape_hicks_henne,  only: hh_spec_type

  implicit none

  ! Single side of airfoil 

  type side_airfoil_type 
    character(3)                  :: name             ! either 'Top' or 'Bot'
    double precision, allocatable :: x(:)
    double precision, allocatable :: y(:)
    double precision, allocatable :: curvature(:)
  end type 

  ! central airfoil type

  type airfoil_type 
    character(:), allocatable     :: name               ! name of the airfoil
    integer                       :: npoint             ! number of points
    double precision, allocatable :: x(:)               ! airfoil coordinates
    double precision, allocatable :: y(:)
    logical :: symmetrical    = .false.     ! #todo ->  init                     ! airfoil symmetrical? -> bot equals top side

    type (side_airfoil_type)      :: top                 ! top side of airfoil
    type (side_airfoil_type)      :: bot                 ! bottom side of airfoil 

    logical :: is_bezier_based = .false.                 ! was airfoil generated by bezier curve
    type (bezier_spec_type)   :: top_bezier              ! bezier curve specification if 'bezier_based'
    type (bezier_spec_type)   :: bot_bezier              ! bezier curve specification if 'bezier_based'

    logical :: is_hh_based = .false.                     ! was airfoil generated by hicks henne functions
    type (hh_spec_type)       :: top_hh                  ! hh specs for top side 
    type (hh_spec_type)       :: bot_hh                  ! hh specs for bot side 
 
  end type airfoil_type

  ! Specify flap
  type flap_spec_type
    logical          :: use_flap
    double precision :: x_flap, y_flap 
    character(3)     :: y_flap_spec
    integer          :: ndegrees                   ! Number of flap degree settings
    double precision, dimension(50) :: degrees     ! used for in 'Worker' 
  end type flap_spec_type
  
!                    
  
  ! Global variables (mainly needed to preserve generality of optimization routines)

  integer, parameter :: max_op_points = 30

  ! Parms for flap handling

  type (flap_spec_type) :: flap_spec
  character(8), dimension(max_op_points) :: flap_selection
  double precision, dimension(max_op_points) :: flap_degrees
  double precision :: min_flap_degrees, max_flap_degrees
  integer :: nflap_optimize          ! Number of op_poins where flap will be optimized
  integer, dimension(max_op_points) :: flap_optimize_points


  ! Parms for shaping geomtery 

  double precision :: initial_perturb

  ! Show more infos during optimization

  logical :: show_details

  ! Subdirectory for all the design files during optimization

  character (*), parameter    :: DESIGN_SUBDIR_POSTFIX = '_temp'
  character (:), allocatable  :: design_subdir, output_prefix


  ! Global Constants

  double precision, parameter :: NOT_DEF_D = -99999d0
  double precision, parameter :: NOT_DEF_I = -99999

end module commons
