! MIT License
! Copyright (C) 2017-2019 Daniel Prosser
! Copyright (c) 2022-2024 Jochen Guenzel

module commons

  ! global types and commons 

  use shape_bezier,       only: bezier_spec_type  
  use shape_hicks_henne,  only: hh_spec_type

  implicit none

  ! --- global types ------------------------------------------------------------

  ! Single side of airfoil 

  type side_airfoil_type 
    character(3)                  :: name             ! either 'Top' or 'Bot'
    double precision, allocatable :: x(:)
    double precision, allocatable :: y(:)
    double precision, allocatable :: curvature(:)
  end type 

  ! the airfoil type

  type airfoil_type 
    character(:), allocatable     :: name               ! name of the airfoil
    integer                       :: npoint             ! number of points
    double precision, allocatable :: x(:)               ! airfoil coordinates
    double precision, allocatable :: y(:)
    logical :: symmetrical    = .false.     ! #todo ->  init                     ! airfoil symmetrical? -> bot equals top side

    type (side_airfoil_type)      :: top                 ! top side of airfoil
    type (side_airfoil_type)      :: bot                 ! bottom side of airfoil 

    logical :: is_bezier_based = .false.                 ! was airfoil generated by bezier curve
    type (bezier_spec_type)   :: top_bezier              ! bezier curve specification if 'bezier_based'
    type (bezier_spec_type)   :: bot_bezier              ! bezier curve specification if 'bezier_based'

    logical :: is_hh_based = .false.                     ! was airfoil generated by hicks henne functions
    type (hh_spec_type)       :: top_hh                  ! hh specs for top side 
    type (hh_spec_type)       :: bot_hh                  ! hh specs for bot side 
 
  end type airfoil_type


  ! --- global statics ------------------------------------------------------------ 

  double precision            :: initial_perturb  ! #todo remove 

  logical                     :: show_details                       ! Show more infos during optimization

  character (*), parameter    :: DESIGN_SUBDIR_POSTFIX = '_temp'
  character (:), allocatable  :: design_subdir                      ! temp directory for all intermediate results
  character (:), allocatable  :: output_prefix                      ! the result output name (of airfoil)


  ! --- Global Constants -----------------------------------------------------

  integer, parameter            :: MAX_NOP = 30
  integer, parameter            :: NOT_DEF_I = -99999
  double precision, parameter   :: NOT_DEF_D = -99999d0

end module commons
